# Generated by Django 6.0.3 on 2026-03-09 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='spin_cost_points',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('LOBBY', 'Lobby'), ('GACHA_SETUP', 'Gacha Setup'), ('GACHA_REVEAL', 'Gacha Reveal'), ('GACHA_SHUFFLE', 'Gacha Shuffle'), ('GACHA_PICK', 'Gacha Pick'), ('GACHA_RESULT', 'Gacha Result'), ('UNDERCOVER_WORD', 'Undercover Word Reveal'), ('UNDERCOVER_DISCUSSION', 'Undercover Discussion'), ('UNDERCOVER_VOTE', 'Undercover Vote'), ('UNDERCOVER_RESULT', 'Undercover Result'), ('SPINWHEEL_READY', 'Spin Wheel Ready'), ('SPINWHEEL_SPIN', 'Spin Wheel Spin'), ('SPINWHEEL_RESULT', 'Spin Wheel Result'), ('GAME_FINISHED', 'Game Finished')], default='LOBBY', max_length=30)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('state_started_at', models.DateTimeField(auto_now_add=True)),
                ('timer_duration', models.IntegerField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='rooms.room')),
            ],
        ),
    ]
