# Generated by Django 6.0.3 on 2026-03-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_spin_cost_points_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='current_state',
            field=models.CharField(choices=[('LOBBY', 'Lobby'), ('GACHA_SETUP', 'Gacha Setup'), ('GACHA_REVEAL', 'Gacha Reveal'), ('GACHA_SHUFFLE', 'Gacha Shuffle'), ('GACHA_PICK', 'Gacha Pick'), ('GACHA_INTERACT', 'Gacha Interaction'), ('GACHA_RESULT', 'Gacha Result'), ('UNDERCOVER_WORD', 'Undercover Word Reveal'), ('UNDERCOVER_DISCUSSION', 'Undercover Discussion'), ('UNDERCOVER_VOTE', 'Undercover Vote'), ('UNDERCOVER_RESULT', 'Undercover Result'), ('SPINWHEEL_READY', 'Spin Wheel Ready'), ('SPINWHEEL_SPIN', 'Spin Wheel Spin'), ('SPINWHEEL_RESULT', 'Spin Wheel Result'), ('GAME_FINISHED', 'Game Finished')], default='LOBBY', max_length=30),
        ),
    ]
