# Generated by Django 6.0.3 on 2026-03-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_gamestate_current_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255, unique=True)),
                ('game_type', models.CharField(default='gacha', max_length=50)),
                ('current_round', models.IntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoundState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('box_state', models.JSONField(default=dict)),
                ('picks', models.JSONField(default=dict)),
                ('abilities', models.JSONField(default=dict)),
                ('eliminations', models.JSONField(default=list)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rooms.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'round_number')},
            },
        ),
    ]
