# Generated by Django 5.2.12 on 2026-03-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotSetting",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "greeting",
                    models.CharField(
                        default="Halo! Ada yang bisa kami bantu?", max_length=255
                    ),
                ),
                (
                    "bubble_label",
                    models.CharField(default="Butuh bantuan?", max_length=60),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chatbot Setting",
                "verbose_name_plural": "Chatbot Settings",
            },
        ),
        migrations.CreateModel(
            name="HelpContact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("contact_value", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HelpOption",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("answer", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=255)),
                ("session_key", models.CharField(blank=True, max_length=64, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-visited_at"],
            },
        ),
    ]
