# Generated by Django 6.0.3 on 2026-03-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rooms.room')),
                ('target_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='players.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='players.player')),
            ],
            options={
                'unique_together': {('room', 'voter')},
            },
        ),
    ]
