# Generated by Django 5.2.12 on 2026-03-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GachaRewardConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[("points", "Points"), ("spins", "Spins")],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=1)),
                ("weight", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
