# Generated by Django 6.0.3 on 2026-03-09 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room')),
            ],
        ),
    ]
