# Generated by Django 6.0.3 on 2026-03-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_points_player_spin_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shield_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='swap_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('eliminated', 'Eliminated')], default='active', max_length=20),
        ),
    ]
