# Generated by Django 6.0.3 on 2026-03-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_shield_count_player_swap_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='double_next_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='jackpot_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pending_ability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='snack_count',
            field=models.IntegerField(default=0),
        ),
    ]
